startup: false
debug : true
timeout: 3600000
wait: 100
settings:
  - 92: 00 #充电阈值第一位，小端序十六进制，15600对应100%,当前值50%
  - 93: 32 #充电阈值第二位，小端序十六进制，15600对应100%,当前值50%
  - 24: 00 #键盘灯超时第一位
  - 25: 00 #键盘灯超时第二位
  - 21: 23 #默认不使用功能键，使用F按键
exit:
  - 92: 00 #充电阈值第一位，小端序十六进制，15600对应100%,当前值50%
  - 93: 64 #充电阈值第二位，小端序十六进制，15600对应100%,当前值50%
